#NOTE:
# -> nginx spawns 2 types of processes:
# 1. Master Process --> USER = ROOT
#   - handles config
#   - initing server
#   - port binding
# 2. Worker Processes --> USER = www-data
#   - handle requests
#   --> requests just need to read the config

server {
    # IPv4
    listen 443 ssl;
    # IPv6
    listen [::]:443 ssl;


    server_name cjuarez.42.fr;

    root /var/www/html;
    index index.php index.html;

    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    location /static/ {
      alias /var/www/static/;
      index index.html;
      try_files $uri $uri/ /static/index.html;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
