# runs in standalone mode
listen=YES

# we dont need lol
listen_ipv6=NO


### AUTH

# user must authenticate
anonymous_enable=NO

# sys_user can login
local_enable=YES



### TIME

# dont use utc by default
use_localtime=YES




### FILE PERMISSION

write_enable=YES

# lock FTP user inside /var/www/html
chroot_local_user=YES

# make /var/www/html writable
allow_writeable_chroot=YES


# enable transfer logging for uploads/downloads
xferlog_enable=YES

# just for active mode; irrelevant for psv mode
connect_from_port_20=YES



### PSV MODE

# we need psv mode
pasv_enable=YES

# must match compose port mapping
pasv_min_port=21100
pasv_max_port=21110



### PATH

# set FTP users root dir to volume path
local_root=/var/www/html


# internal safe empty dir used by vsftpd during chroot handling
# should exist and owned by root and not writeable by FTP user
secure_chroot_dir=/var/run/vsftpd/empty



### DAEMON

# do not daemonize
# as we need the process to run in the foreground
#   as PID 1 for the container to stay alive lol
background=NO

# need to disable could block syscall otherwise
seccomp_sandbox=NO


### LOGGING

# log all ftp commands
log_ftp_protocol=YES


# enable transfer logging
xferlog_enable=YES
# transfer log location
xferlog_file=/var/log/vsftpd.log

# use vsftpd format ( more detailed )
xferlog_std_format=NO
# protocol log location
vsftpd_log_file=/var/log/vsftpd.log





# DISABLE SSL
ssl_enable=NO
